modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/Vazkii/Psi"
license="https://psi.vazkii.net/license.php"

[[mods]]
modId="psi"
displayName="Psi"
version="${version}"
authors="Vazkii, Wiiv, WireSegal, Kamefrede, Williewillus, Hubry"
description='''
Psionic Spellcasting Instruments
'''
[[dependencies.psi]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.18-45,)"
    side="BOTH"


[[dependencies.psi]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="AFTER"
    side="BOTH"